In [18]:
%matplotlib inline

from IPython.display import Image,display

from numpy import pi

from qutip import *
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload 
from scipy.optimize import fsolve
import pdb

class LocalOperator:
    def __init__(self, dict_of_ops):
        # list of 1 qubit ops and indexes of the shape (op, i) 
        # for example {1:sigmaz(), 5: sigmax(), 10:hadamard()}
        self.dict_of_ops = dict_of_ops
        self.update_d()
        
    def update_d(self):
        if len(self.dict_of_ops) == 0:
            self.d = 0
        else:
            self.d = max(self.dict_of_ops.keys()) + 1 
        
    def full_form(self, n = None):
        if n == None : n = self.d
            
        full_list = []
        for i in range(n):
            
            if i in self.dict_of_ops.keys():
                full_list.append(self.dict_of_ops[i])
            else:
                full_list.append(qeye(2))
        return tensor(full_list)
    
    def tensor(self, other):
        #new is copy of old
        new = LocalOperator(self.dict_of_ops.copy())
        for index,op in other.dict_of_ops.items():
            if index in new.dict_of_ops.keys():
                new.dict_of_ops[index] *=  other.dict_of_ops[index]
            else:
                new.dict_of_ops[index] = other.dict_of_ops[index]
        new.update_d()
        return new
    
    def __mul__(self, other):
        return self.tensor(other)
    
    def __sub__(self, other):
        new = LocalOperator(self.dict_of_ops.copy())
        if (sorted( self.dict_of_ops.keys() ) !=
            sorted( other.dict_of_ops.keys() ) ) :
             raise TypeError('Local operator operate on different qubits') 
                
        for index,op in other.dict_of_ops.items():
            new.dict_of_ops[index] -=  other.dict_of_ops[index]
            
        new.dict_of_ops = {x:y for (x,y) in new.dict_of_ops.items() if y.norm() != 0  }
        new.update_d()
        return new
    
    def add(self, other):
        new = LocalOperator(self.dict_of_ops.copy())
        if (sorted( self.dict_of_ops.keys() ) !=
            sorted( other.dict_of_ops.keys() ) ) :
             raise TypeError('Local operator operate on different qubits') 
                
        for index,op in other.dict_of_ops.items():
            new.dict_of_ops[index] +=  other.dict_of_ops[index]
            
        new.dict_of_ops = {x:y for (x,y) in new.dict_of_ops.items() if y.norm() != 0  }
        new.update_d()
        return new
    
    def norm(self):
        if self.d == 0 : return 0
        ret = 1
        for op in self.dict_of_ops.values():
            ret *= op.norm()
        return ret
    
    def __repr__(self):
        return str(self.dict_of_ops)

In [17]:
# H1 = LocalOperator({0:sigmaz(), 1:sigmaz()})
# H2 = LocalOperator({1:sigmax(), 2:sigmax()})
# H3 = LocalOperator({2:sigmaz(), 3:sigmaz()})
# print ("Sanity check :\n(H1 and H2) and (H2 and H3) not commuting ",(H1*H2-H2*H1).norm(), (H2*H3-H3*H2).norm())
# print ("H1-H3 are commuting ", (H1*H3-H3*H1).norm())

Sanity check :
(H1 and H2) and (H2 and H3) not commuting  4.0 4.0
H1-H3 are commuting  0


In [18]:
# (H1*H3 - H3*H1).norm()

0

In [19]:
# a = {1:0,2:4}

In [ ]:
# list(filter(None,a.values()))

In [ ]:
# l1.dict_of_ops

In [ ]:
# Qobj(((0,1),(1,0)))\

In [3]:
# basis(2) - basis(4)

TypeError: Incompatible quantum object dimensions

In [14]:
from importlib import reload
from Two_non_commutings import plot_commutations,plot_operator
import XXZZham
reload(XXZZham)

<module 'XXZZham' from '/home/oryonatan/qutip/dorit/XXZZham.py'>

In [9]:
t = XXZZham.XXZZ_term(1,2,15)

In [10]:
t.get_oper()

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 15.   0.   0.  15.]
 [  0. -15.  15.   0.]
 [  0.  15. -15.   0.]
 [ 15.   0.   0.  15.]]

In [12]:
t.get_commuting_form(2)

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = [16, 16], type = oper, isherm = True
Qobj data =
[[ 15.   0.   0.  15.   0.  15.  15.   0.   0.  15.  15.   0.  15.   0.
    0.  15.]
 [  0.  15.  15.   0.  15.   0.   0.  15.  15.   0.   0.  15.   0.  15.
   15.   0.]
 [  0.  15.  15.   0.  15.   0.   0.  15.  15.   0.   0.  15.   0.  15.
   15.   0.]
 [ 15.   0.   0.  15.   0.  15.  15.   0.   0.  15.  15.   0.  15.   0.
    0.  15.]
 [  0.  15.  15.   0. -15.   0.   0. -15.  15.   0.   0.  15.   0. -15.
  -15.   0.]
 [ 15.   0.   0.  15.   0. -15. -15.   0.   0.  15.  15.   0. -15.   0.
    0. -15.]
 [ 15.   0.   0.  15.   0. -15. -15.   0.   0.  15.  15.   0. -15.   0.
    0. -15.]
 [  0.  15.  15.   0. -15.   0.   0. -15.  15.   0.   0.  15.   0. -15.
  -15.   0.]
 [  0.  15.  15.   0.  15.   0.   0.  15. -15.   0.   0. -15.   0. -15.
  -15.   0.]
 [ 15.   0.   0.  15.   0.  15.  15.   0.   0. -15. -15.   0. -15.   0.
    0. -15.]
 [ 15.   0.   0.  15.   0.  15.  15.   0

In [29]:
t.get_oper().dims

[[2, 2], [2, 2]]

In [27]:
t.get_commuting_form(2)

[[2, 2, 2, 2], [2, 2, 2, 2]]

In [97]:
rand_unitary(4,dims = [[2, 2], [2, 2]])

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = False
Qobj data =
[[ 0.99144289-0.00189981j  0.01544004-0.01313915j  0.01796392-0.02511114j
  -0.12517778+0.0018999j ]
 [-0.01433298+0.01425641j  0.58094507+0.44187362j -0.45300855+0.40949693j
  -0.23258893+0.199599j  ]
 [-0.02054635+0.02309701j -0.51741703+0.32321183j  0.41205986+0.50967362j
  -0.29895246+0.32851942j]
 [ 0.09904699+0.0765688j  -0.30740501-0.01246539j -0.42790845+0.11608654j
   0.66952378+0.49480286j]]

In [99]:
psi  = rand_unitary(4,dims = [[2, 2], [2, 2]]) * tensor([basis(2,0)]*2)
psi

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 0.47682669+0.36640828j]
 [-0.34928809+0.19768154j]
 [-0.38777361+0.54810226j]
 [-0.02722359+0.1605476j ]]

In [100]:
o_small = t.get_oper()

In [101]:
expect(o_small,psi)

5.3332443803879315

In [102]:
o_big = t.get_commuting_form(2)

In [103]:
psi_0n = tensor(psi,tensor(basis(2,1),basis(2,0)))

In [104]:
expect(o_big,psi_0n)

5.3332443803879315

In [107]:
print(psi_0n)

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = [16, 1], type = ket
Qobj data =
[[ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [ 0.47682669+0.36640828j]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [-0.34928809+0.19768154j]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [-0.38777361+0.54810226j]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [ 0.00000000+0.j        ]
 [-0.02722359+0.1605476j ]
 [ 0.00000000+0.j        ]]
